services:
  db:
    image: mysql:8
    container_name: fastapi-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: academicapp
      MYSQL_USER: admin
      MYSQL_PASSWORD: Password#0*5
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
